name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

#      - name: Run unit tests for gateway
#        run: |
#          cd v3/gateway
#          python -m pytest test_main.py
#
#      - name: Run unit tests for cars-service
#        run: |
#          cd v3/cars-service
#          python -m pytest test_main.py
#
#      - name: Run unit tests for rental-service
#        run: |
#          cd v3/rental-service
#          python -m pytest test_main.py
#
#      - name: Run unit tests for payment-service
#        run: |
#          cd v3/payment-service
#          python -m pytest test_main.py

      - name: Build images
        timeout-minutes: 10
        run: docker compose build

      - name: Run containers
        timeout-minutes: 5
        run: |
          docker compose up -d
          ./scripts/wait-script.sh
        env:
          WAIT_PORTS: 8080,8070,8060,8050

      - name: Run API Tests
        timeout-minutes: 5
        run: ./scripts/test-script.sh
        env:
          VARIANT: v3
          SERVICE_NAME: payment-service
          PORT_NUMBER: 8050

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

#      - name: Github auto grader mark
#        uses: Romanow/google-sheet-autograder-marker@v1.0
#        with:
#          google_token: ${{secrets.GOOGLE_API_KEY}}
#          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
#          homework_number: 3
#          user_column: 'D'
#          column_offset: 'F'
#          mark: "'+"

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v
